### ISSUE TITLE
open-redir-harder lab not working as intended

### ISSUE THREAD

**Issue by blabla1337** [blabla1337/skf-labs#82]
SKF open-redir-harder Docker container.
 
If you click the “Go to new website” button it redirects to: /redirect?newurl=/newsite
 
It should redir to: /redirect?newurl=newsite

need to check with the writeup and why its not working as it should :)

**Comment by mzfr** [comment]
@blabla1337 I'll look into this.

**Comment by mzfr** [comment]
@blabla1337 it looks like the issue is the template `action`.
In the template of that challenge the POST action is set to `/newsite`([Line 59](https://github.com/blabla1337/skf-labs/blob/master/Url-redirection-harder/templates/index.html#L59)).

This is the issue you were talking about right? If yes then I'll just make a PR about it.

**Comment by blabla1337** [comment]
Thanks fixed it!
